### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Setup Environment & Run Packages**</div>

In every project, before everything, we should import all needed libraries. It makes sense that if we need more libraries during the project, we add here.

In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import datetime
from datetime import date

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Load Data**</div>

First of all, we import the raw datasets

In [2]:
customers = pd.read_csv('customers.csv')
properties = pd.read_csv('properties.csv')

Then we should merge two datasets into one.

In [3]:
df = pd.merge(customers, properties, on='CustomerID', how='left')

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Variable Names**</div>

Column names provide a clear identification of the data contained within each column. By reviewing the column names, we can quickly understand the type of information stored in each column. This helps we make sense of the data and interpret it correctly.

In [4]:
df.columns

Index(['Unnamed: 0_x', 'CustomerID', 'entity', 'name', 'surname', 'birth_date',
       'sex', 'country', 'state', 'purpose', 'deal_satisfaction', 'mortgage',
       'source', 'Unnamed: 0_y', 'homeid', 'building', 'date_sale', 'type',
       'property#', 'area', 'price', 'status'],
      dtype='object')

We don't need some columns and we remove them.

In [5]:
df = df.drop(['Unnamed: 0_x', 'entity', 'name', 'surname', 'state', 'Unnamed: 0_y', 'building','property#', 'status'] , axis=1)

In [6]:
col_names = {
    'CustomerID':'CustomerID',
    'birth_date' : 'DoB',
    'sex' : 'Gender',
    'country' : 'Country',
    'purpose' : 'Purpose',
    'deal_satisfaction' : 'Satisfaction',
    'mortgage' : 'Mortgage',
    'source' : 'Source',
    'homeid' : 'PropertyID',
    'date_sale' : 'Date',
    'type' : 'Type',
    'area' : 'Area',
    'price' : 'Price',
}

df = df.rename(columns = col_names)

Now, we change the order of the columns to have better view on them.

In [7]:
col_order = ['CustomerID', 'DoB', 'Gender', 'Country', 'Purpose', 'Mortgage', 'Source', 'PropertyID', 'Type',
            'Area','Price','Satisfaction', 'Date']

df = df[col_order]

In [8]:
df.head(1)

CustomerID  DoB Gender Country     Purpose Mortgage  Source  PropertyID  \
0      C0001  NaN    NaN     USA  Investment       No  Agency        1005   

     Type    Area         Price  Satisfaction      Date  
0  Office  410.71  $117,564.07              5  3/1/2004

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Data Type Conversion**</div>

Checking the data types is an important step in data cleaning because it helps ensure the consistency, accuracy, and reliability of the data.

In [9]:
df.dtypes

CustomerID       object
DoB              object
Gender           object
Country          object
Purpose          object
Mortgage         object
Source           object
PropertyID        int64
Type             object
Area            float64
Price            object
Satisfaction      int64
Date             object
dtype: object

We must check whether the data type of variables is correct or not.
* `CustomerID`: String *(Object)*
* `DoB`: Date *(Object)*
* `Gender`: Nominal Categorical *(Object)*
* `Country`: Nominal Categorical *(Object)*
* `Purpose`: Nominal Categorical *(Object)*
* `Mortgage`: Nominal Categorical *(Object)*
* `Source`: Nominal Categorical *(Object)*
* `PropertyID`: String *(Object)*
* `Type`: Nominal Categorical *(Object)*
* `Area`: Number *(float64-int64)*
* `Date`: Date *(Object)*
* `Price`: Number *(float64-int64)*
* `Satisfaction`: Ordinal Categorical *(Object)*

Based on the above, we have to change data type:
 <li>`PropertyID` from <span style="color:white; background-color:red">int64</span> to <span style="color:white; background-color:blue">object</span>
 <li>`Price` from <span style="color:white; background-color:red">object</span> to <span style="color:white; background-color:blue">int64</span>
 <li>`Satisfaction` from <span style="color:white; background-color:red">int64</span> to <span style="color:white; background-color:blue">object</span>
  <li>`DoB` & `Date` from <span style="color:white; background-color:red">object</span> to <span style="color:white; background-color:blue">date</span>

In [10]:
df['PropertyID'].unique()

array([1005, 1002, 1044, 1043, 1033, 1038, 1018, 1021, 1036, 1045, 1035,
       1009, 1015, 1049, 1032, 1017, 1041, 1025, 1026, 1012, 1023, 1003,
       1006, 1027, 1011, 1029, 1030, 1007, 1008, 2023, 2030, 1016, 1040,
       1031, 1039, 1024, 2054, 2041, 2032, 3027, 1046, 2007, 2039, 2057,
       2037, 2005, 2050, 2026, 2015, 2033, 3015, 2029, 3007, 3030, 2020,
       2040, 2038, 2042, 4035, 4022, 3050, 2010, 2036, 2049, 2003, 2004,
       2006, 2044, 2022, 2011, 2047, 2014, 3001, 3043, 2025, 2018, 2009,
       2017, 2013, 3047, 2046, 2016, 2008, 2019, 2021, 2027, 2052, 3006,
       3044, 4025, 3031, 2048, 2028, 2043, 3049, 3034, 5033, 5035, 5039,
       2056, 2012, 3016, 3020, 3029, 5030, 3038, 3039, 3022, 3054, 3055,
       4031, 2035, 3008, 3040, 3025, 5016, 5019, 3059, 2034, 3021, 4051,
       3014, 2002, 3028, 3042, 3002, 3004, 3032, 3013, 3010, 3018, 2001,
       3046, 2051, 3019, 3011, 3026, 3005, 3033, 5013, 3012, 3048, 2024,
       4034, 3036, 4019, 5034, 4041, 4024, 4010, 40

In [11]:
df['PropertyID'] = df['PropertyID'].astype('object')
print(df['PropertyID'].dtype)

object


In [12]:
df['Satisfaction'].unique()

array([5, 2, 3, 4, 1], dtype=int64)

In [13]:
df['Satisfaction'] = df['Satisfaction'].astype('object')
print(df['Satisfaction'].dtype)

object


In [14]:
df['Price'].unique()

array(['$117,564.07 ', '$410,932.67 ', '$229,464.71 ', '$377,313.56 ',
       '$412,856.56 ', '$207,581.43 ', '$191,389.87 ', '$218,585.92 ',
       '$317,473.86 ', '$248,525.12 ', '$238,811.06 ', '$317,196.40 ',
       '$208,930.81 ', '$467,083.31 ', '$215,410.28 ', '$432,679.91 ',
       '$480,545.81 ', '$382,041.13 ', '$179,674.08 ', '$300,385.62 ',
       '$261,579.89 ', '$193,660.62 ', '$198,841.70 ', '$276,759.18 ',
       '$222,947.21 ', '$246,331.90 ', '$246,172.68 ', '$250,312.53 ',
       '$246,050.40 ', '$219,373.41 ', '$214,341.34 ', '$224,076.84 ',
       '$234,172.39 ', '$265,467.68 ', '$196,220.05 ', '$235,762.34 ',
       '$306,363.64 ', '$225,050.52 ', '$306,878.46 ', '$245,572.79 ',
       '$503,790.23 ', '$196,142.19 ', '$293,876.27 ', '$382,277.15 ',
       '$229,581.78 ', '$257,183.48 ', '$297,008.97 ', '$198,075.99 ',
       '$228,170.03 ', '$205,085.40 ', '$207,281.59 ', '$310,223.29 ',
       '$231,552.33 ', '$215,774.28 ', '$241,671.52 ', '$224,463.87 ',
      

In [15]:
df['Price'] = pd.to_numeric(df['Price'].str.replace('[\$,]' , '', regex=True), errors='coerce')

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Handle Missing Values**</div>

Checking for missing values is an important step in data cleaning because missing values can have a significant impact on the quality and reliability of the data analysis. In this dataset, we must handle missing values, because we want to construct ML model and having null values in ML model would cause to have inaccurate prediction. First, we create a function to see how many missing valus we have.

In [16]:
def null(df):
    null_values = pd.DataFrame(df.isnull().sum())
    null_values[1] = null_values[0]/len(df)
    null_values.columns=['count','%pct']
    filtered_null = null_values[null_values['%pct']>0]
    return filtered_null

In [17]:
null(df)

count      %pct
DoB        16  0.082474
Gender     16  0.082474

To deal with null missing values, based on the data type and the percentage of null values, we can take different measures.

* **Strategy (1)**: The percentage is less than 5% : Remove missing values
* **Strategy (2)**: The percentage is between 5% and 10% and type is categorical : Impute with mode
* **Strategy (3)**: The percentage is more than 10% : Impute with KNN or ask expert

In [18]:
df = df.dropna(subset=['DoB','Gender'])

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Feature Engineering**</div>

We should convert date values to date format.

In [19]:
df['DoB'] = pd.to_datetime(df['DoB'], format='%m/%d/%Y')
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')

Now we can cacluate age instead of having date of birth.

In [20]:
df['Age']=2023-df['DoB'].dt.year
df=df.drop(['DoB'],axis=1)

col_order = ['CustomerID', 'Age', 'Gender', 'Country', 'Purpose', 'Mortgage', 'Source', 'PropertyID', 'Type',
            'Area','Price','Satisfaction', 'Date']

df = df[col_order]

Then, we just extract year and month name for `Date` column.

In [21]:
df['Year']=df['Date'].dt.year
df['Month']=df['Date'].dt.month_name()
df=df.drop(['Date'],axis=1)

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Handle Duplicants**</div>

Duplicate rows can compromise the integrity of the dataset. If we have multiple identical rows, it can lead to inaccurate statistical analysis, misleading results, and duplicate entries in downstream processes. By identifying and removing duplicate rows, we ensure that the data accurately represents the underlying information.

In [22]:
df.duplicated().sum()

0

Also, we can see whether we have a customer that have the same property twice or not, regardless the other factors, because other factors might change.

In [23]:
df[df.duplicated(subset=['CustomerID', 'PropertyID'])]

Empty DataFrame
Columns: [CustomerID, Age, Gender, Country, Purpose, Mortgage, Source, PropertyID, Type, Area, Price, Satisfaction, Year, Month]
Index: []

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Number Sanity Check**</div>

Saity check is an important step in data cleaning because it helps identify and handle data values that fall outside the expected or valid range for a particular variable. In addition, we can check how many percentage of values are negative.

In [24]:
num_var = ['Age', 'Area', 'Price']

for i in range(len(num_var)):
    print('{}, min: {}, max: {}'.format(num_var[i] ,df[num_var[i]].min() ,df[num_var[i]].max()))

Age, min: 37, max: 92
Area, min: 579.75, max: 1942.5
Price, min: 153466.71, max: 503790.23


### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Categorical Possible Range**</div>

By checking the possible range for categorical variables, we can identify any unexpected or erroneous values. This helps ensure the data's integrity and validity. It allows us to misspellings, or other inconsistencies in the categorical variable values.

In [25]:
def cat_checker(Var):
    unique_value=pd.Series(df[Var].unique()).sort_values().values
    return unique_value

In [26]:
df.sample(1)

CustomerID  Age Gender Country     Purpose Mortgage   Source PropertyID  \
113      C0103   87      M     USA  Investment       No  Website       3040   

          Type    Area      Price Satisfaction  Year Month  
113  Apartment  670.89  204292.49            2  2007  June

In [27]:
cat_checker('Gender')

array(['F', 'M'], dtype=object)

In [28]:
cat_checker('Purpose')

array(['Investment', 'Personal Use'], dtype=object)

In [29]:
cat_checker('Mortgage')

array(['No', 'Yes'], dtype=object)

In [30]:
cat_checker('Source')

array(['Agency', 'Client', 'Website'], dtype=object)

In [31]:
cat_checker('Type')

array(['Apartment', 'Office'], dtype=object)

In [32]:
cat_checker('Satisfaction')

array([1, 2, 3, 4, 5], dtype=object)

### <div style="color:white; background-color:#666; padding: 8px; border-radius: 5px">**Data Analysis**</div>

In this part, we want to do some statistical analysis on data breakdown on country. The questions that we are trying to answer are the following:

**Age Distribution of Customers**

In [35]:
def age_dist(country):
    country_df = df[df['Country'] == country]
    age_range = pd.cut(
        country_df['Age'],
        bins = [0, 30, 50, 70, 100],
        labels = ['0-30' , '31-50', '51-70' , '71-100']
    )
    return age_range.value_counts()

**Average Price**

In [40]:
def avg_price(country):
    country_df = df[df['Country'] == country]
    return country_df['Price'].mean()

unq_country = df['Country'].unique()

for country in unq_country:
    average_price = avg_price(country)
    print(f"Average price in {country}: {average_price}")

Average price in USA: 271020.37464968156
Average price in Belgium: 229075.47
Average price in Russia: 278828.83499999996
Average price in USA : 316315.58666666667
Average price in Denmark: 257183.48
Average price in Canada: 274069.38428571424
Average price in Mexico: 338181.18
Average price in UK: 220142.68
Average price in Germany: 205098.21


**Distribution of Sales across Months and Years**

In [42]:
def sales_dist(country):
    country_df = df[df['Country'] == country]
    return country_df.groupby(['Year', 'Month']).size()

**Percentage of Sales from each source**

In [49]:
def ads_effect(country):
    country_df = df[df['Country'] == country]
    return country_df['Source'].value_counts(normalize=True)*100

**Correlation Analysis among age, price and area**

In [54]:
def cor_age_price_area(country):
    country_df = df[df['Country'] == country]
    
    return country_df[['Age','Price', 'Area']].corr()